# Generated by Django 5.2.12 on 2026-08-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('kicker', models.CharField(blank=True, help_text='Small label above the title, e.g. "Admissions open"', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_link', models.CharField(blank=True, help_text='e.g. #popular-courses or a full https:// URL', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
