# Generated by Django 5.2.12 on 2026-08-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bannerslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerslide',
            name='image_url',
            field=models.URLField(blank=True, help_text='Used only if no image is uploaded above'),
        ),
    ]
