# Generated by Django 5.2.12 on 2026-08-05 10:30

from django.db import migrations

DEFAULT_SLIDES = [
    {
        'order': 0,
        'kicker': 'Admissions open',
        'title': 'Sliding Advertisement Banner',
        'subtitle': 'New batch for SSC, Railway & Banking starts 12 August.',
        'button_text': 'See the batch plan',
        'button_link': '#popular-courses',
        'image_url': 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1400&q=70',
    },
    {
        'order': 1,
        'kicker': 'Free this week',
        'title': '10 Years of PYQs, Solved',
        'subtitle': 'Download chapter-wise papers with video solutions — no fee, no login wall.',
        'button_text': 'Download papers',
        'button_link': '#results',
        'image_url': 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1400&q=70',
    },
    {
        'order': 2,
        'kicker': 'Test series',
        'title': 'Mock Test Every Sunday',
        'subtitle': 'Real exam timing, All-India rank, and a doubt session the same evening.',
        'button_text': 'Book a free mock',
        'button_link': '#contact',
        'image_url': 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1400&q=70',
    },
]


def seed_slides(apps, schema_editor):
    BannerSlide = apps.get_model('myapp', 'BannerSlide')
    if BannerSlide.objects.exists():
        return
    for data in DEFAULT_SLIDES:
        BannerSlide.objects.create(**data)


def remove_seeded_slides(apps, schema_editor):
    BannerSlide = apps.get_model('myapp', 'BannerSlide')
    BannerSlide.objects.filter(title__in=[s['title'] for s in DEFAULT_SLIDES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_bannerslide_image_url'),
    ]

    operations = [
        migrations.RunPython(seed_slides, remove_seeded_slides),
    ]
