# Generated by Django 5.2.12 on 2026-08-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(help_text='Short scrolling line, e.g. "SSC CGL 2026 notification released — 4,500+ vacancies"', max_length=200)),
                ('detail', models.TextField(blank=True, help_text='Longer text shown in the popup when a student taps this notification')),
                ('link', models.URLField(blank=True, help_text='Official link (apply page, PDF, etc). Shown as a button in the popup.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
