# Generated by Django 5.2.12 on 2026-08-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_seed_default_chatbot_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(blank=True, default='New batches starting', max_length=80)),
                ('badge_highlight', models.CharField(blank=True, default='Enroll free', help_text='Shown after the small dot in the badge pill', max_length=80)),
                ('heading_prefix', models.CharField(blank=True, default='Crack Any', help_text='First line of the heading', max_length=100)),
                ('heading_highlight', models.CharField(blank=True, default='Govt Exam', help_text='Highlighted (orange) part of the heading', max_length=100)),
                ('heading_suffix', models.CharField(blank=True, default='with confidence', help_text='Rest of the heading, after the highlight', max_length=100)),
                ('subtitle', models.TextField(blank=True, default='Live classes, free PYQs, mock tests, expert guidance, doubt solving, and a focused roadmap for serious exam aspirants.')),
                ('primary_btn_text', models.CharField(blank=True, default='Start learning free', max_length=50)),
                ('primary_btn_link', models.CharField(blank=True, default='#admission', max_length=300)),
                ('secondary_btn_text', models.CharField(blank=True, default='Browse courses', max_length=50)),
                ('secondary_btn_link', models.CharField(blank=True, default='#popular-courses', max_length=300)),
                ('stat1_number', models.CharField(blank=True, default='12,400+', max_length=20)),
                ('stat1_label', models.CharField(blank=True, default='Students taught', max_length=60)),
                ('stat2_number', models.CharField(blank=True, default='820', max_length=20)),
                ('stat2_label', models.CharField(blank=True, default='Final selections', max_length=60)),
                ('stat3_number', models.CharField(blank=True, default='1,100+', max_length=20)),
                ('stat3_label', models.CharField(blank=True, default='Free video lessons', max_length=60)),
                ('badge1_value', models.CharField(blank=True, default='98%', help_text='e.g. 98%', max_length=10)),
                ('badge1_title', models.CharField(blank=True, default='Success Rate', max_length=60)),
                ('badge1_subtitle', models.CharField(blank=True, default='Govt exam selections', max_length=100)),
                ('badge2_value', models.CharField(blank=True, default='AI', help_text='e.g. AI', max_length=10)),
                ('badge2_title', models.CharField(blank=True, default='Free Access', max_length=60)),
                ('badge2_subtitle', models.CharField(blank=True, default='Mock tests & guidance', max_length=100)),
                ('visual_type', models.CharField(choices=[('illustration', 'Default illustration'), ('image', 'Image'), ('video', 'Video')], default='illustration', max_length=15)),
                ('visual_image', models.ImageField(blank=True, help_text='Used when visual type is "Image". Recommended size: 520×420px.', null=True, upload_to='hero/')),
                ('visual_video_url', models.URLField(blank=True, help_text='Used when visual type is "Video". Paste a normal YouTube/Vimeo link, or a direct .mp4 link.')),
            ],
            options={
                'verbose_name': 'Hero section',
                'verbose_name_plural': 'Hero section',
            },
        ),
    ]
