# Generated by Django 5.2.12 on 2026-08-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_herosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='illustration_style',
            field=models.CharField(choices=[('study', 'Studying with a laptop'), ('reading', 'Reading a book'), ('graduate', 'Graduation success'), ('online_class', 'Live online class'), ('exam', 'Writing an exam')], default='study', help_text='Used when visual type is "Default illustration".', max_length=20),
        ),
    ]
