# Generated by Django 5.2.12 on 2026-08-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_herosection_illustration_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUpdateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('current_affairs', 'Current Affairs'), ('daily_news', 'Daily News')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('visual_type', models.CharField(choices=[('illustration', 'Default illustration'), ('image', 'Image')], default='illustration', max_length=15)),
                ('illustration_style', models.CharField(choices=[('reading', 'Reading on a couch'), ('quiz', 'On a video call'), ('news', 'Reading the newspaper')], default='reading', max_length=15)),
                ('image', models.ImageField(blank=True, help_text='Used when visual type is "Image". Recommended size: 340×190px.', null=True, upload_to='daily_updates/')),
            ],
            options={
                'verbose_name': 'Daily update card',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='DailyUpdatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('current_affairs', 'Current Affairs'), ('daily_news', 'Daily News')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='daily_updates/posts/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
