# Generated by Django 5.2.12 on 2026-08-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_dailyupdatecard_dailyupdatepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('course', models.CharField(choices=[('SSC & Railways', 'SSC & Railways'), ('Banking & Insurance', 'Banking & Insurance'), ('NEET & JEE foundation', 'NEET & JEE foundation')], max_length=50)),
                ('preferred_batch', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
