# Generated by Django 5.2.12 on 2026-08-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_admissionregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Show the "Install App" button on the site')),
                ('app_name', models.CharField(blank=True, default='Manjunath Academy', help_text='Full app name shown during install', max_length=100)),
                ('short_name', models.CharField(blank=True, default='Manjunath', help_text='Short name shown under the home screen icon (12 characters or less looks best)', max_length=30)),
                ('description', models.CharField(blank=True, default='Coaching for SSC, Railway, Banking, NEET & JEE exams.', max_length=200)),
                ('theme_color', models.CharField(blank=True, default='#F97316', help_text='Hex color, e.g. #F97316. Used for the browser/app toolbar color.', max_length=7)),
                ('background_color', models.CharField(blank=True, default='#FFFCFA', help_text='Hex color, e.g. #FFFCFA. Used for the splash screen background.', max_length=7)),
                ('android_icon', models.ImageField(blank=True, help_text='Square icon for Android/Chrome. Recommended: 512×512px PNG.', null=True, upload_to='pwa/')),
                ('ios_icon', models.ImageField(blank=True, help_text='Square icon for iOS/Safari home screen. Recommended: 180×180px PNG. Falls back to the Android icon if left empty.', null=True, upload_to='pwa/')),
            ],
            options={
                'verbose_name': 'App (PWA) settings',
                'verbose_name_plural': 'App (PWA) settings',
            },
        ),
    ]
