# Generated by Django 5.2.12 on 2026-08-05 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Optional emoji icon, e.g. 📘', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('test_series', 'Test Series'), ('video_course', 'Video Course'), ('elibrary', 'E-Library')], max_length=20)),
                ('name', models.CharField(max_length=200, verbose_name='Course name')),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('enable_folders', models.BooleanField(default=False, help_text='Turn on if this course is organized into folders/chapters')),
                ('enable_validity', models.BooleanField(default=False, help_text='Turn on if access to this course expires after a validity period')),
                ('about', models.TextField(blank=True, verbose_name='About course')),
                ('thumbnail', models.ImageField(blank=True, help_text='Recommended size: 400×240px (16:10).', null=True, upload_to='courses/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='myapp.category')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
