# Generated by Django 5.2.12 on 2026-08-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_seed_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='test_type',
            field=models.CharField(blank=True, choices=[('mock_test', 'Mock Test'), ('practice_test', 'Practice Test'), ('sectional_test', 'Sectional Test'), ('sample_papers', 'Sample Papers'), ('previous_year_paper', 'Previous Year Paper')], help_text='Used for Test Series only — e.g. Mock Test, Practice Test.', max_length=20),
        ),
    ]
