# Generated by Django 5.2.12 on 2026-08-05 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_seed_dummy_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enable_folders',
        ),
        migrations.AddField(
            model_name='course',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Used for E-Library only. Upload the book/notes as a PDF.', null=True, upload_to='elibrary_pdfs/'),
        ),
        migrations.AddField(
            model_name='course',
            name='validity_unit',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('months', 'Months')], default='months', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='validity_value',
            field=models.PositiveIntegerField(blank=True, help_text='Length of access, e.g. 6', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video_file',
            field=models.FileField(blank=True, help_text='Used for Video Courses only. Upload the course video (MP4 recommended).', null=True, upload_to='course_videos/'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', 'Single Correct Answer'), ('multiple', 'Multiple Correct Answers'), ('numeric', 'Numeric Answer'), ('true_false', 'True / False'), ('fill_blank', 'Fill in the Blank')], default='single', max_length=20)),
                ('text', models.TextField(verbose_name='Question')),
                ('option_a', models.CharField(blank=True, max_length=300)),
                ('option_b', models.CharField(blank=True, max_length=300)),
                ('option_c', models.CharField(blank=True, max_length=300)),
                ('option_d', models.CharField(blank=True, max_length=300)),
                ('correct_answer', models.CharField(blank=True, help_text='Single/True-False: e.g. A or True. Multiple: comma-separated, e.g. A,C. Numeric/Fill-in-the-blank: the exact value.', max_length=300)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(limit_choices_to={'course_type': 'test_series'}, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='myapp.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='myapp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
