# Generated by Django 5.2.12 on 2026-08-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_course_author_course_duration_minutes_course_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
