# Generated by Django 5.2.12 on 2026-08-05 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_seed_store_career_questions_and_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=150)),
                ('min_education', models.CharField(choices=[('10th', '10th Pass'), ('12th', '12th Pass'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate')], default='10th', max_length=15)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('min_height_cm', models.PositiveIntegerField(blank=True, help_text='Leave blank if height does not matter', null=True)),
                ('allowed_gender', models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10)),
                ('marital_status', models.CharField(choices=[('any', 'Any'), ('unmarried_only', 'Unmarried Only')], default='any', max_length=20)),
                ('allowed_states', models.CharField(blank=True, help_text='Comma-separated states this job is open to. Leave blank to allow every state.', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Eligibility criteria',
                'ordering': ['order', 'job_name'],
            },
        ),
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_heading', models.CharField(blank=True, default='Academic Excellence', max_length=150)),
                ('results_subtitle', models.CharField(blank=True, default='Giving wings to a millions dreams, a million more to go', max_length=250)),
                ('gallery_heading', models.CharField(blank=True, default='Life At Manjunath Academy', max_length=150)),
                ('gallery_subtitle', models.CharField(blank=True, default='Classrooms, felicitations, and the moments in between.', max_length=250)),
                ('about_heading', models.CharField(blank=True, default="India's Most Trusted Free Exam Prep Platform", max_length=200)),
                ('about_para1', models.TextField(blank=True, default='Online Kaksha was built with one belief — every Indian aspirant deserves world-class government exam preparation without paying a rupee. We provide meticulously crafted PYQs, daily quizzes, and study notes covering Banking, SSC, Railway, CDS, and AFCAT.')),
                ('about_para2', models.TextField(blank=True, default='Founded by educators who cleared competitive exams themselves, we understand the grind. Our platform is designed to save your time, sharpen your knowledge, and maximise your selection chances.')),
                ('about_checklist', models.TextField(blank=True, default='100% free access to PYQs and daily quizzes\nCurated study notes for every major govt exam\nExpert faculty with years of exam experience\nMobile-friendly platform — study anywhere, anytime\nRegular updates aligned with latest exam patterns\nDedicated doubt-solving and community support', help_text='One point per line.')),
                ('about_badge_value', models.CharField(blank=True, default='50,000+', max_length=20)),
                ('about_badge_label', models.CharField(blank=True, default='Students', max_length=60)),
                ('about_image', models.ImageField(blank=True, help_text='Recommended size: 760×560px.', null=True, upload_to='homepage/')),
            ],
            options={
                'verbose_name': 'Homepage content',
                'verbose_name_plural': 'Homepage content',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1, help_text='Difficulty order — lower levels are asked first')),
                ('text', models.TextField(verbose_name='Question')),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1)),
                ('prize_label', models.CharField(blank=True, help_text='Shown on the money ladder, e.g. ₹10,000', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResultHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='results/')),
                ('caption', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='force_free',
            field=models.BooleanField(default=False, help_text='Grant free access even if a price is set above', verbose_name='Make this free'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(blank=True, default='Manjunath Academy', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about',
            field=models.TextField(blank=True, default='Coaching for government exams, NEET and JEE. Classes online and at the Lucknow centre.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_address',
            field=models.CharField(blank=True, default='Hazratganj, Lucknow, Uttar Pradesh', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_email',
            field=models.EmailField(blank=True, default='hello@manjunathacademy.in', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_phone',
            field=models.CharField(blank=True, default='+915220000000', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='🎓', help_text='Emoji shown on the bundle card, e.g. 🎓', max_length=10)),
                ('badge_label', models.CharField(blank=True, help_text='e.g. All Subjects Included', max_length=100)),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=2)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='bundles', to='myapp.course')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BundlePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='myapp.bundle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(choices=[('10th', '10th Pass'), ('12th', '12th Pass'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate')], max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('height_cm', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(choices=[('unmarried', 'Unmarried'), ('married', 'Married')], max_length=15)),
                ('matched_jobs', models.TextField(blank=True, help_text='Snapshot of job names the candidate was eligible for at submission time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
