# Generated by Django 5.2.12 on 2026-08-06 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_seed_bundles_criteria_quiz_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(help_text='e.g. Maths Faculty', max_length=100)),
                ('department', models.CharField(choices=[('teaching', 'Teaching'), ('admin', 'Administration'), ('support', 'Support Staff'), ('management', 'Management')], default='teaching', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('salary', models.DecimalField(decimal_places=2, default=0, help_text='Monthly salary in ₹', max_digits=10)),
                ('date_of_joining', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck when a staff member leaves — keeps their history intact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('fees', 'Student Fees'), ('salary', 'Staff Salary'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('marketing', 'Marketing'), ('supplies', 'Supplies'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. SSC CGL Batch — Term 1 Fee', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=10)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'On Leave')], default='present', max_length=10)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='myapp.staffmember')),
            ],
            options={
                'verbose_name_plural': 'Staff attendance',
                'ordering': ['-date'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
