# Generated by Django 5.2.12 on 2026-08-06 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_seed_dummy_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Shown to students, e.g. WELCOME50', max_length=40, unique=True)),
                ('description', models.CharField(blank=True, help_text='Internal note about this coupon', max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage off'), ('flat', 'Flat amount off')], default='percentage', max_length=12)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 20) or flat rupees (e.g. 100) depending on type above', max_digits=8)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Caps the discount for percentage coupons. Leave blank for no cap.', max_digits=8, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Coupon only applies if the order is at least this much', max_digits=8)),
                ('applies_to', models.CharField(choices=[('all', 'Everything'), ('course', 'Courses & test series'), ('bundle', 'Bundles'), ('store', 'Store products')], default='all', max_length=12)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total times this coupon can be used across all students. Leave blank for unlimited.', null=True)),
                ('per_user_limit', models.PositiveIntegerField(default=1, help_text='How many times a single student may use this coupon')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=12)),
                ('object_id', models.PositiveIntegerField()),
                ('amount_before', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount_after', models.DecimalField(decimal_places=2, max_digits=9)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='myapp.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
