# Generated by Django 5.2.12 on 2026-08-06 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_coupon_couponredemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('completion', 'Certificate of Completion'), ('achievement', 'Certificate of Achievement'), ('participation', 'Certificate of Participation'), ('appreciation', 'Certificate of Appreciation')], default='completion', max_length=15)),
                ('recipient_name', models.CharField(blank=True, help_text="Leave blank to use the student's account name", max_length=150)),
                ('course_name', models.CharField(help_text='e.g. SSC CGL Test Series 2026', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Optional extra line, e.g. for scoring 95% in the final test', max_length=250)),
                ('certificate_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('issue_date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
