# Generated by Django 5.2.12 on 2026-08-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_conditions', 'Terms & Conditions'), ('refund_cancellation', 'Refund & Cancellation Policy'), ('shipping_delivery', 'Shipping & Delivery Policy'), ('contact_us', 'Contact Us'), ('disclaimer', 'Disclaimer')], max_length=25, unique=True)),
                ('title', models.CharField(blank=True, help_text='Leave blank to use the default title shown above', max_length=150)),
                ('content', models.TextField(blank=True, help_text='Separate paragraphs with a blank line. Start a line with "- " for a bullet point.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
