# Generated by Django 5.2.12 on 2026-08-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_classroom_classroommember'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_provider_name', models.CharField(blank=True, help_text='e.g. MSG91, Twilio, Fast2SMS — just a label shown in the admin panel.', max_length=100)),
                ('sms_api_url', models.URLField(blank=True, help_text='The HTTP endpoint your SMS provider gives you for sending a message via POST.')),
                ('sms_api_key', models.CharField(blank=True, max_length=255)),
                ('sms_sender_id', models.CharField(blank=True, help_text='Sender ID / from name shown to the recipient, if your provider needs one.', max_length=30)),
                ('smtp_host', models.CharField(blank=True, max_length=200)),
                ('smtp_port', models.PositiveIntegerField(blank=True, default=587, null=True)),
                ('smtp_username', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=200)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254)),
                ('smtp_from_name', models.CharField(blank=True, default='Manjunath Academy', max_length=100)),
            ],
            options={
                'verbose_name': 'SMS & Email settings',
                'verbose_name_plural': 'SMS & Email settings',
            },
        ),
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(help_text='Email address or phone number the OTP was sent to.', max_length=255)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
