# Generated by Django 5.2.12 on 2026-08-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_notificationprovidersettings_otprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_enabled', models.BooleanField(default=False)),
                ('google_client_id', models.CharField(blank=True, max_length=255)),
                ('google_client_secret', models.CharField(blank=True, max_length=255)),
                ('facebook_enabled', models.BooleanField(default=False)),
                ('facebook_app_id', models.CharField(blank=True, max_length=255)),
                ('facebook_app_secret', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'SSO settings',
                'verbose_name_plural': 'SSO settings',
            },
        ),
    ]
