# Generated by Django 5.2.12 on 2026-08-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_ssosettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, help_text='e.g. SSC, Banking, Railways', max_length=100)),
                ('description', models.TextField(blank=True, help_text='What this date is for — exam date, admit card release, application deadline, etc.')),
                ('event_date', models.DateField()),
                ('official_link', models.URLField(blank=True, help_text='Official notification / apply link, if available')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date', 'order'],
            },
        ),
    ]
