# Generated by Django 5.2.12 on 2026-08-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_dailyquizattempt_quizzoneattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropboxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, help_text='Generated from the Dropbox App Console for your app.', max_length=500)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('last_backup_status', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Dropbox settings',
                'verbose_name_plural': 'Dropbox settings',
            },
        ),
    ]
