# Generated by Django 5.2.12 on 2026-08-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_dropboxsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropboxsettings',
            name='access_token',
        ),
    ]
