# Generated by Django 5.2.12 on 2026-08-19 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_remove_dropboxsettings_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(help_text='Recommended: transparent PNG, roughly 200×100px.', upload_to='brands/')),
                ('link', models.URLField(blank=True, help_text="Optional — opens when the logo is clicked. Leave blank if it shouldn't link anywhere.")),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, help_text='Full article content shown on the details page. Basic HTML (e.g. <p>, <b>, <ul>, <table>) is allowed.'),
        ),
        migrations.AddField(
            model_name='notification',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Featured image shown at the top of the full details page.', null=True, upload_to='notifications/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, help_text='Full headline for the details page. Leave blank to reuse the ticker text above.', max_length=250),
        ),
        migrations.AddField(
            model_name='notification',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube/Vimeo link embedded in the details page.'),
        ),
        migrations.CreateModel(
            name='NotificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notifications/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='myapp.notification')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
