# Generated by Django 5.2.12 on 2026-08-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_brand_notification_body_notification_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='device_type',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iPhone/iPad'), ('desktop', 'Desktop'), ('other', 'Other')], help_text='Detected from the signup device', max_length=10),
        ),
        migrations.AlterField(
            model_name='admissionregistration',
            name='course',
            field=models.CharField(help_text='Course/batch the student is interested in', max_length=150),
        ),
    ]
