# Generated by Django 5.2.12 on 2026-08-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_coursedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizGameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_music', models.FileField(blank=True, help_text='MP3 played on loop in the background while the quiz game is open.', null=True, upload_to='quiz_game/')),
            ],
            options={
                'verbose_name': 'Quiz game settings',
                'verbose_name_plural': 'Quiz game settings',
            },
        ),
    ]
