# Generated by Django 5.2.12 on 2026-08-25 07:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_quizgamesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyupdatepost',
            options={'ordering': ['-event_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='dailyupdatepost',
            name='body_hi',
            field=models.TextField(blank=True, help_text='Optional. Leave blank to fall back to the English body.', verbose_name='Body (Hindi)'),
        ),
        migrations.AddField(
            model_name='dailyupdatepost',
            name='body_kn',
            field=models.TextField(blank=True, help_text='Optional. Leave blank to fall back to the English body.', verbose_name='Body (Kannada)'),
        ),
        migrations.AddField(
            model_name='dailyupdatepost',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='The date this news is about (used to group Current Affairs by date).'),
        ),
        migrations.AddField(
            model_name='dailyupdatepost',
            name='news_category',
            field=models.CharField(blank=True, choices=[('National', 'National'), ('International', 'International'), ('State', 'State'), ('Sports', 'Sports')], help_text='Used for Current Affairs only — groups the post under this heading for its date.', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyupdatepost',
            name='title_hi',
            field=models.CharField(blank=True, help_text='Optional. Leave blank to fall back to the English title.', max_length=200, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='dailyupdatepost',
            name='title_kn',
            field=models.CharField(blank=True, help_text='Optional. Leave blank to fall back to the English title.', max_length=200, verbose_name='Title (Kannada)'),
        ),
    ]
