# Generated by Django 5.2.12 on 2026-08-25 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_alter_dailyupdatepost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Application Start Date, Exam Date, Application Fee', max_length=150)),
                ('value', models.CharField(help_text='e.g. 05 Aug 2026, ₹500', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_rows', to='myapp.notification')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
