# Generated by Django 5.2.12 on 2026-08-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_notificationtablerow'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_device_label',
            field=models.CharField(blank=True, default='', help_text='Browser/device of the current active session.', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_login_at',
            field=models.DateTimeField(blank=True, help_text='When the current active session was created.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_session_key',
            field=models.CharField(blank=True, default='', help_text="Session key of this account's one currently-allowed login.", max_length=40),
        ),
    ]
