# Generated by Django 5.2.12 on 2026-08-25 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_customuser_active_device_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('video_course', 'Video Course'), ('elibrary', 'E-Library')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(blank=True, help_text='Optional emoji icon, e.g. 📁', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='myapp.coursefolder')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Used for Video Courses / E-Library only — organizes items into folders and subfolders.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='myapp.coursefolder'),
        ),
    ]
