# Generated by Django 5.2.12 on 2026-08-26 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_coursefolder_course_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='folder',
        ),
        migrations.AddField(
            model_name='course',
            name='enable_folders',
            field=models.BooleanField(default=False, help_text="Organize this course's videos or PDFs inside folders and subfolders."),
        ),
        migrations.CreateModel(
            name='CourseContentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_folders', to='myapp.course')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='myapp.coursecontentfolder')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='coursedocument',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='myapp.coursecontentfolder'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='myapp.coursecontentfolder'),
        ),
        migrations.DeleteModel(
            name='CourseFolder',
        ),
    ]
