# Generated by Django 5.2.12 on 2026-08-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_remove_course_folder_course_enable_folders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Used for E-Library only. Upload the book/notes as a PDF.', max_length=500, null=True, upload_to='elibrary_pdfs/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Recommended size: 400×240px (16:10).', max_length=500, null=True, upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_file',
            field=models.FileField(blank=True, help_text='Used for Video Courses only. Upload the course video (MP4 recommended).', max_length=500, null=True, upload_to='course_videos/'),
        ),
        migrations.AlterField(
            model_name='coursedocument',
            name='pdf_file',
            field=models.FileField(help_text='Upload a PDF document.', max_length=500, upload_to='elibrary_pdfs/collection/'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='video_file',
            field=models.FileField(help_text='Upload an MP4 or other browser-supported video file.', max_length=500, upload_to='course_videos/playlist/'),
        ),
    ]
