# Generated by Django 5.2.12 on 2026-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_real_dashboard_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='access_label',
            field=models.CharField(blank=True, default='Full Course', help_text='Shown next to the clock icon on the card, e.g. Lifetime Access, Full Course', max_length=30),
        ),
        migrations.AddField(
            model_name='bundle',
            name='students_label',
            field=models.CharField(blank=True, default='10,000+', help_text='Shown next to the students icon on the card, e.g. 21,230', max_length=30),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='badge_label',
            field=models.CharField(blank=True, help_text='e.g. All Subjects Included. For multiple small tags (like subjects), separate with commas, e.g. Mathematics, English, GK', max_length=150),
        ),
    ]
