# Generated by Django 5.2.12 on 2026-08-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_bundle_access_label_bundle_students_label_and_more'),
        ('myapp', '0063_bundle_image'),
    ]

    operations = [
    ]
