# Generated by Django 5.2.12 on 2026-08-26 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_staffsalarypayment_studentattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUpdatePostTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Repo Rate, Series Result, Mission Name', max_length=150)),
                ('value', models.CharField(help_text='e.g. 6.5%, India won 3-2, EOS-09', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_rows', to='myapp.dailyupdatepost')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
