# Generated by Django 5.2.12 on 2026-08-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_dailyupdateposttablerow'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Optional per-language text, e.g. {"hi": {"text": "...", "option_a": "..."}}. Missing languages fall back to the English fields above.'),
        ),
    ]
