# Generated by Django 5.2.12 on 2026-09-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_question_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquizattempt',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
