# Generated by Django 5.2.12 on 2026-09-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0071_daily_quiz_attempt_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamInstructionsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_text', models.TextField(default='Your clock is synchronized with the server. The countdown at the top of the question page shows the remaining time available for you to complete the examination. When the timer reaches zero, the examination will submit itself automatically — you need not submit it manually.\nThe question palette on the right side of the test shows the status of every question using the colors below.', help_text='One instruction per line. Shown as a numbered list on the test instructions page and inside the exam.')),
            ],
            options={
                'verbose_name': 'Exam instructions settings',
                'verbose_name_plural': 'Exam instructions settings',
            },
        ),
    ]
