# Generated by Django 5.2.12 on 2026-09-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0072_exam_instructions_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinstructionssettings',
            name='agreement_text',
            field=models.TextField(default='I have read and understood the instructions. All computer hardware allotted to me is in proper working condition. I declare that I am not in possession of, not wearing, and not carrying any prohibited gadget like a mobile phone, Bluetooth device, etc., or any prohibited material into the examination. I agree that if I fail to adhere to the instructions, I shall be liable to be debarred from this test and/or to disciplinary action, which may include a ban from future tests/examinations.', help_text='Shown next to the agreement checkbox students must accept before starting a test.'),
        ),
    ]
