# Generated by Django 5.2.12 on 2026-09-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_exam_instructions_agreement_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo_key',
            field=models.CharField(choices=[('general', 'General exams'), ('school', 'School education'), ('staff', 'Staff selection'), ('railway', 'Railway'), ('banking', 'Banking'), ('medical', 'Medical'), ('engineering', 'Engineering'), ('civil', 'Civil services'), ('defence', 'Defence'), ('teaching', 'Teaching'), ('state', 'State exams'), ('police', 'Police'), ('judiciary', 'Judiciary'), ('insurance', 'Insurance'), ('agriculture', 'Agriculture'), ('postal', 'Postal'), ('entrance', 'Entrance exams'), ('computer', 'Computer & IT')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='examtickeritem',
            name='logo_key',
            field=models.CharField(choices=[('general', 'General exams'), ('school', 'School education'), ('staff', 'Staff selection'), ('railway', 'Railway'), ('banking', 'Banking'), ('medical', 'Medical'), ('engineering', 'Engineering'), ('civil', 'Civil services'), ('defence', 'Defence'), ('teaching', 'Teaching'), ('state', 'State exams'), ('police', 'Police'), ('judiciary', 'Judiciary'), ('insurance', 'Insurance'), ('agriculture', 'Agriculture'), ('postal', 'Postal'), ('entrance', 'Entrance exams'), ('computer', 'Computer & IT')], default='general', help_text='Vector logo displayed beside this exam category.', max_length=20),
        ),
    ]
