# Generated by Django 5.2.12 on 2026-09-03 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Used by the Test Series exam hierarchy (Exam → Sub-exam → Subject → Topic). Leave blank for a top-level category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.category'),
        ),
    ]
