# Generated by Django 5.2.12 on 2026-09-03 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0076_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Used for Test Series. Tag with one, several, or every relevant exam/subject — students will see this test under each one.', related_name='tagged_test_series', to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Used for Video Courses and E-Library. Test Series use the Categories field below instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='myapp.category'),
        ),
    ]
