# Generated by Django 5.2.12 on 2026-09-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0078_alter_category_logo_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended size: 1600×600px.', null=True, upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Recommended size: 300×300px, square.', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='dailyupdatepost',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image shown on the full Current Affairs article. Recommended size: 1200×675px.', null=True, upload_to='daily_updates/posts/'),
        ),
        migrations.AlterField(
            model_name='dailyupdatepost',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Compact image used on the homepage and Current Affairs listing. Falls back to the main image. Recommended size: 400×225px.', null=True, upload_to='daily_updates/posts/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='Recommended size: 1200×800px.', upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Featured image shown at the top of the full details page. Recommended size: 1200×630px.', null=True, upload_to='notifications/'),
        ),
        migrations.AlterField(
            model_name='notificationimage',
            name='image',
            field=models.ImageField(help_text='Recommended size: 1200×800px.', upload_to='notifications/gallery/'),
        ),
        migrations.AlterField(
            model_name='resulthighlight',
            name='image',
            field=models.ImageField(help_text='Recommended size: 600×600px.', upload_to='results/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Recommended size: 512×512px, square PNG.', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Recommended size: 200×60px, transparent PNG.', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Recommended size: 300×300px, square.', null=True, upload_to='staff/'),
        ),
    ]
